"""Small injected ports; no review or lifecycle capability in analysis."""
from typing import Protocol
from prompt_optimizer.domain import Dataset
from prompt_optimizer.domain.failures import FailureCase, FailureCluster, FailureDraft, HumanReview


class FailureSanitizer(Protocol):
    def sanitize(self, trace: object) -> FailureCase: ...


class FailureAnalyzer(Protocol):
    def analyze(self, failures: tuple[FailureCase, ...]) -> tuple[FailureCluster, ...]: ...


class FailureStore(Protocol):
    def save_import(self, failures: tuple[FailureCase, ...], drafts: tuple[FailureDraft, ...]) -> None: ...
    def get_draft(self, draft_id: str) -> FailureDraft: ...
    def get_review(self, draft_id: str) -> HumanReview | None: ...
    def save_review(self, review: HumanReview) -> None: ...
    def revise(self, draft: FailureDraft) -> None: ...


class ReviewedDatasetWriter(Protocol):
    def write(self, dataset: Dataset, destination: str) -> None: ...
